version: 2
project_name: web-indexer
before:
  hooks:
    - go mod tidy
builds:
  - id: "web-indexer"
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{.Version}}"
    goos:
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
    main: .
    binary: web-indexer
archives:
  - id: "tarball"
    ids:
      - "web-indexer"
    formats: ['tar.gz']
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: ['zip']
    files: []
    #   - src: LICENSE
    #   - src: README.md
snapshot:
  version_template: "{{ .Tag }}-next"
checksum:
  name_template: 'checksums.txt'
dockers:
  - id: web-indexer-amd64
    ids:
      - web-indexer
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - ghcr.io/joshbeard/web-indexer/web-indexer:{{ .Env.SNAPSHOT_TAG }}-amd64
    extra_files:
      - "entrypoint.sh"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    skip_push: false
  - id: web-indexer-arm64
    ids:
      - web-indexer
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - ghcr.io/joshbeard/web-indexer/web-indexer:{{ .Env.SNAPSHOT_TAG }}-arm64
    extra_files:
      - "entrypoint.sh"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    skip_push: false

docker_manifests:
  - name_template: ghcr.io/joshbeard/web-indexer/web-indexer:{{ .Env.SNAPSHOT_TAG }}
    image_templates:
      - ghcr.io/joshbeard/web-indexer/web-indexer:{{ .Env.SNAPSHOT_TAG }}-amd64
      - ghcr.io/joshbeard/web-indexer/web-indexer:{{ .Env.SNAPSHOT_TAG }}-arm64

nfpms:
  - id: 'testpkg'
    vendor: "Josh Beard"
    maintainer: "Josh Beard <josh@jbeard.dev>"
    homepage: "http://github.com/joshbeard/web-indexer"
    license: "MIT"
    description: Generate static indexes for local paths and S3 buckets
    #prerelease: beta1
    release: "1"
    priority: "extra"
    section: vcs
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    rpm: {}
    deb: {}
    apk: {}
    archlinux:
      packager: Josh Beard <josh@jbeard.dev>