# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - go mod tidy

gitlab_urls:
  api: https://oaklab.hu/api/v4
  download: https://oaklab.hu
  use_package_registry: true
  use_job_token: true

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - name_template: |-
      {{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}
    formats:
      - binary
    files:
      - none*

checksum:
  name_template: 'checksums.txt'

nfpms:
  - maintainer: Kristof Bach <crys@crys.hu>
    homepage: https://oaklab.hu/crys/web-indexer
    license: MIT
    description: Generate static indexes for local paths and S3 buckets
    priority: optional
    section: utils
    formats:
      - deb
    umask: 0o022
