name: PR Build

on:
  pull_request:
    types: [opened, synchronize, labeled]

permissions:
  contents: read # Needed for checkout
  packages: write # Needed to push Docker image to GHCR
  pull-requests: write # Needed to comment on PRs

jobs:
  build_pr_snapshot:
    name: Build PR Snapshot
    if: github.event.pull_request.user.login == 'joshbeard' && contains(github.event.pull_request.labels.*.name, 'dev-build')
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: auto

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # GoReleaser needs full history

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'
          cache: true

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser for PR Snapshot
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean --snapshot --skip=validate --config .goreleaser-dev.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SNAPSHOT_TAG: dev-pr${{ github.event.pull_request.number }}

      - name: Find existing comment
        uses: peter-evans/find-comment@v3
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Dev build has been published!'

      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          body: |
            🚀 Dev build has been published!

            **Image tag:** `ghcr.io/${{ github.repository }}:dev-pr${{ github.event.pull_request.number }}`

            **Example usage:**
            ```bash
            docker pull ghcr.io/${{ github.repository }}:dev-pr${{ github.event.pull_request.number }}
            docker run --rm ghcr.io/${{ github.repository }}:dev-pr${{ github.event.pull_request.number }}
            ```
          edit-mode: replace