name: PR Build

on:
  pull_request:
    types: [opened, synchronize, labeled]

permissions:
  contents: read # Needed for checkout
  packages: write # Needed to push Docker image to GHCR

jobs:
  build_pr_snapshot:
    name: Build PR Snapshot
    if: github.event.pull_request.user.login == 'joshbeard' && contains(github.event.pull_request.labels.*.name, 'dev-build')
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: auto

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # GoReleaser needs full history

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'
          cache: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser for PR Snapshot
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean --snapshot --skip=validate --config .goreleaser-dev.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SNAPSHOT_TAG: dev-pr${{ github.event.pull_request.number }}

      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🚀 Dev build has been published!

            **Image tag:** `ghcr.io/${{ github.repository }}:dev-pr${{ github.event.pull_request.number }}`

            **Example usage:**
            ```bash
            docker pull ghcr.io/${{ github.repository }}:dev-pr${{ github.event.pull_request.number }}
            docker run --rm ghcr.io/${{ github.repository }}:dev-pr${{ github.event.pull_request.number }}
            ```