name: "Lint & Test"
on:
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: auto

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
          check-latest: true # Ensure the cache isn't stale.

      - name: check-vuln
        run: make check-vuln

      - name: Run gosec
        # Use a more recent version of gosec
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec -exclude-dir=vendor ./...
        env:
          GOTOOLCHAIN: auto

  lint:
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: auto
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
          check-latest: true # Ensure the cache isn't stale.

      - name: Lint
        run: make lint

  test:
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: auto
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
          check-latest: true # Ensure the cache isn't stale.

      - name: Test
        run: make coverage
